# Site settings
name: 武神酱丶
location: 石家庄
company: 石家庄铁道大学
position: 学生
github: https://github.com/wushenjiang
facebook: https://www.facebook.com/
phone: 15383119674
email: 1098577802@qq.com

baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

